services:
  db:
    image: postgres:16-alpine
    # container_name: team-notes-db   # remove to avoid conflicts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team_notes
    ports:
      - "5433:5432"
    volumes:
      - team_notes_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d team_notes"]
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  team_notes_db: